name: Go

on:
  push:
    branches: [ "main" ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      env:
        MIGRATION_DRIVER: cockroachdb
        DB_URL: ${{ secrets.DB_URL }}
      run: go test -p=1 -v -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
